# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto

require 'google/protobuf'


descriptor_data = "\n\necho.proto\x12\x04\x65\x63ho\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\x0b\x42urnRequest\x12\n\n\x02ms\x18\x01 \x01(\x05\")\n\tEchoReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x05\x32\x95\x01\n\x0b\x45\x63hoService\x12*\n\x04\x45\x63ho\x12\x11.echo.EchoRequest\x1a\x0f.echo.EchoReply\x12*\n\x04\x42urn\x12\x11.echo.BurnRequest\x1a\x0f.echo.EchoReply\x12.\n\x04\x43hat\x12\x11.echo.EchoRequest\x1a\x0f.echo.EchoReply(\x01\x30\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Echo
  EchoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("echo.EchoRequest").msgclass
  BurnRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("echo.BurnRequest").msgclass
  EchoReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("echo.EchoReply").msgclass
end
