# frozen_string_literal: true

source "https://rubygems.org"
gem "gritz-async", git: "https://github.com/gritzrpc/gritz-async.git", branch: "main"
gem "gritz-core", git: "https://github.com/gritzrpc/gritz-core.git", branch: "main"
gem "gritz-native", path: ".."
