# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reflection_other.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x16reflection_other.proto\x12\x12reflection_fixture\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n\x05Other\x12&\n\x02\x61t\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module ReflectionFixture
  Other = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reflection_fixture.Other").msgclass
end
