# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reflection_types.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'reflection_other_pb'


descriptor_data = "\n\x16reflection_types.proto\x12\x12reflection_fixture\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16reflection_other.proto\"\x82\x02\n\x07Request\x12&\n\x02\x61t\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x06nested\x18\x02 \x01(\x0b\x32\".reflection_fixture.Request.Nested\x12\x30\n\x05state\x18\x03 \x01(\x0e\x32!.reflection_fixture.Request.State\x12(\n\x05other\x18\x04 \x01(\x0b\x32\x19.reflection_fixture.Other\x1a\x17\n\x06Nested\x12\r\n\x05value\x18\x01 \x01(\t\"\x1f\n\x05State\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05READY\x10\x01*\x05\x08\x64\x10\xc8\x01\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module ReflectionFixture
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reflection_fixture.Request").msgclass
  Request::Nested = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reflection_fixture.Request.Nested").msgclass
  Request::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reflection_fixture.Request.State").enummodule
  Reply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("reflection_fixture.Reply").msgclass
end
