# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reflection_service.proto

require 'google/protobuf'

require 'reflection_types_pb'


descriptor_data = "\n\x18reflection_service.proto\x12\x12reflection_fixture\x1a\x16reflection_types.proto2N\n\tInspector\x12\x41\n\x07Inspect\x12\x1b.reflection_fixture.Request\x1a\x19.reflection_fixture.Reply:*\n\x05label\x12\x1b.reflection_fixture.Request\x18\x64 \x01(\t"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module ReflectionFixture
end
