# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: reflection_service.proto for package 'reflection_fixture'

require 'grpc'
require 'reflection_service_pb'

module ReflectionFixture
  module Inspector
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'reflection_fixture.Inspector'

      rpc :Inspect, ::ReflectionFixture::Request, ::ReflectionFixture::Reply
    end

    Stub = Service.rpc_stub_class
  end
end
