# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Products.proto

require 'google/protobuf'


descriptor_data = "\n\x0eProducts.proto\x12\x03rpc\"2\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\"\x1b\n\rGetProductReq\x12\n\n\x02id\x18\x01 \x01(\r\"/\n\x0eGetProductResp\x12\x1d\n\x07product\x18\x01 \x01(\x0b\x32\x0c.rpc.Product\"/\n\x0eGetProductsReq\x12\x0e\n\x06search\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\r\"4\n\x12\x43reateProductsResp\x12\x1e\n\x08products\x18\x01 \x03(\x0b\x32\x0c.rpc.Product2\xf2\x01\n\x08Products\x12\x37\n\nGetProduct\x12\x12.rpc.GetProductReq\x1a\x13.rpc.GetProductResp\"\x00\x12\x34\n\x0bGetProducts\x12\x13.rpc.GetProductsReq\x1a\x0c.rpc.Product\"\x00\x30\x01\x12;\n\x0e\x43reateProducts\x12\x0c.rpc.Product\x1a\x17.rpc.CreateProductsResp\"\x00(\x01\x12:\n\x16\x43reateProductsInStream\x12\x0c.rpc.Product\x1a\x0c.rpc.Product\"\x00(\x01\x30\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Rpc
  Product = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Product").msgclass
  GetProductReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetProductReq").msgclass
  GetProductResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetProductResp").msgclass
  GetProductsReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetProductsReq").msgclass
  CreateProductsResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.CreateProductsResp").msgclass
end
